-- tests/navigation_history_buttons_spec.lua
-- Unit tests for navigation-history-buttons module (custom stack mode)
-- Run with: nvim --headless -c "PlenaryBustedDirectory tests/ {minimal_init = 'tests/minimal_init.lua'}"

local nav = require("nvim-launch.navigation-history-buttons")

describe("navigation-history-buttons", function()
  before_each(function()
    -- Clear all buffers and reset history
    vim.cmd("silent! %bwipeout!")
    nav._reset()
  end)

  describe("can_go_back", function()
    it("returns false with empty history", function()
      assert.is_false(nav.can_go_back())
    end)

    it("returns true after recording multiple positions", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      nav._record(true)
      vim.api.nvim_win_set_cursor(0, { 20, 0 })
      nav._record(true)
      assert.is_true(nav.can_go_back())
    end)
  end)

  describe("can_go_forward", function()
    it("returns false with empty history", function()
      assert.is_false(nav.can_go_forward())
    end)

    it("returns false when at end of history", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      nav._record(true)
      assert.is_false(nav.can_go_forward())
    end)

    it("returns true after going back", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      nav._record(true)
      vim.api.nvim_win_set_cursor(0, { 20, 0 })
      nav._record(true)
      nav.go_back()
      assert.is_true(nav.can_go_forward())
    end)
  end)

  describe("go_back", function()
    it("does not error when history is empty", function()
      assert.has_no.errors(function()
        nav.go_back()
      end)
    end)

    it("moves cursor to previous position", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      nav._record(true)
      vim.api.nvim_win_set_cursor(0, { 30, 0 })
      nav._record(true)
      nav.go_back()
      local pos = vim.api.nvim_win_set_cursor and vim.api.nvim_win_get_cursor(0)
      assert.equals(1, pos[1])
    end)

    it("navigates across buffers", function()
      local buf1 = vim.api.nvim_create_buf(true, false)
      local buf2 = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_buf_set_lines(buf1, 0, -1, false, { "buf1 line1" })
      vim.api.nvim_buf_set_lines(buf2, 0, -1, false, { "buf2 line1" })

      vim.api.nvim_set_current_buf(buf1)
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      nav._record(true)

      vim.api.nvim_set_current_buf(buf2)
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      nav._record(true)

      nav.go_back()
      assert.equals(buf1, vim.api.nvim_get_current_buf())
    end)
  end)

  describe("go_forward", function()
    it("does not error when history is empty", function()
      assert.has_no.errors(function()
        nav.go_forward()
      end)
    end)

    it("moves cursor to next position after go_back", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      nav._record(true)
      vim.api.nvim_win_set_cursor(0, { 30, 0 })
      nav._record(true)
      nav.go_back()
      nav.go_forward()
      local pos = vim.api.nvim_win_get_cursor(0)
      assert.equals(30, pos[1])
    end)
  end)

  describe("back-forward-back-forward stability", function()
    it("does not get stuck oscillating", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))

      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      nav._record(true)
      vim.api.nvim_win_set_cursor(0, { 20, 0 })
      nav._record(true)
      vim.api.nvim_win_set_cursor(0, { 40, 0 })
      nav._record(true)

      -- back back forward forward should return to 40
      nav.go_back()
      assert.equals(20, vim.api.nvim_win_get_cursor(0)[1])
      nav.go_back()
      assert.equals(1, vim.api.nvim_win_get_cursor(0)[1])
      nav.go_forward()
      assert.equals(20, vim.api.nvim_win_get_cursor(0)[1])
      nav.go_forward()
      assert.equals(40, vim.api.nvim_win_get_cursor(0)[1])
    end)

    it("truncates forward history on new navigation", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))

      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      nav._record(true)
      vim.api.nvim_win_set_cursor(0, { 20, 0 })
      nav._record(true)
      vim.api.nvim_win_set_cursor(0, { 40, 0 })
      nav._record(true)

      -- Go back then record a new position — forward history should be gone
      nav.go_back()
      vim.api.nvim_win_set_cursor(0, { 35, 0 })
      nav._record(true)

      assert.is_false(nav.can_go_forward())
      local state = nav._get_state()
      assert.equals(3, #state.history)
    end)
  end)

  describe("_record", function()
    it("deduplicates same buffer+line", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "line1" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      nav._record(true)
      nav._record(true)
      nav._record(true)
      local state = nav._get_state()
      assert.equals(1, #state.history)
    end)

    it("skips small jumps within same buffer when not forced", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      nav._record(true)
      vim.api.nvim_win_set_cursor(0, { 5, 0 })
      nav._record(false) -- only 4 lines, should be skipped
      local state = nav._get_state()
      assert.equals(1, #state.history)
    end)

    it("records large jumps within same buffer", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      nav._record(true)
      vim.api.nvim_win_set_cursor(0, { 20, 0 })
      nav._record(false) -- 19 lines, should be recorded
      local state = nav._get_state()
      assert.equals(2, #state.history)
    end)

    it("skips non-file buffers", function()
      local buf = vim.api.nvim_create_buf(false, true) -- scratch buffer
      vim.api.nvim_set_current_buf(buf)
      vim.bo[buf].buftype = "nofile"
      nav._record(true)
      local state = nav._get_state()
      assert.equals(0, #state.history)
    end)

    it("respects max_history limit", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 200))
      -- Record more than default max
      for i = 1, 110 do
        vim.api.nvim_win_set_cursor(0, { math.min(i, 200), 0 })
        nav._record(true)
      end
      local state = nav._get_state()
      assert.is_true(#state.history <= 100)
    end)
  end)

  describe("get_bufferline_components", function()
    it("returns two components with correct text", function()
      local components = nav.get_bufferline_components()
      assert.equals(2, #components)
      assert.equals(" ◀ ", components[1].text)
      assert.equals(" ▶ ", components[2].text)
    end)

    it("uses inactive highlight when history is empty", function()
      local components = nav.get_bufferline_components()
      assert.equals("NavHistoryButtonInactive", components[1].link)
      assert.equals("NavHistoryButtonInactive", components[2].link)
    end)

    it("uses active highlight for back when history exists", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      nav._record(true)
      vim.api.nvim_win_set_cursor(0, { 20, 0 })
      nav._record(true)
      local components = nav.get_bufferline_components()
      assert.equals("NavHistoryButtonActive", components[1].link)
      assert.equals("NavHistoryButtonInactive", components[2].link)
    end)
  end)

  describe("setup", function()
    it("does nothing when enabled is false", function()
      assert.has_no.errors(function()
        nav.setup({ enabled = false })
      end)
    end)

    it("registers mouse mappings when mouse_buttons is true", function()
      nav.setup({ enabled = true, mouse_buttons = true, bufferline_buttons = false, keys = {} })
      local maps = vim.api.nvim_get_keymap("n")
      local found_x1 = false
      local found_x2 = false
      for _, m in ipairs(maps) do
        if m.lhs == "<X1Mouse>" then found_x1 = true end
        if m.lhs == "<X2Mouse>" then found_x2 = true end
      end
      assert.is_true(found_x1, "X1Mouse mapping should be registered")
      assert.is_true(found_x2, "X2Mouse mapping should be registered")
    end)

    it("registers user commands", function()
      nav.setup({ enabled = true, mouse_buttons = false, bufferline_buttons = false, keys = {} })
      local cmds = vim.api.nvim_get_commands({})
      assert.is_not_nil(cmds["NavigateBack"])
      assert.is_not_nil(cmds["NavigateForward"])
    end)
  end)
end)
